services:
  - type: web
    name: ecommerce-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
    healthCheckPath: /
    
databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free

